// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: proto/gop2pdme.proto

package gop2pdme

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// P2PServiceClient is the client API for P2PService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type P2PServiceClient interface {
	Connect(ctx context.Context, in *Post, opts ...grpc.CallOption) (P2PService_ConnectClient, error)
	Disconnect(ctx context.Context, in *Post, opts ...grpc.CallOption) (*Empty, error)
	Messages(ctx context.Context, opts ...grpc.CallOption) (P2PService_MessagesClient, error)
}

type p2PServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewP2PServiceClient(cc grpc.ClientConnInterface) P2PServiceClient {
	return &p2PServiceClient{cc}
}

func (c *p2PServiceClient) Connect(ctx context.Context, in *Post, opts ...grpc.CallOption) (P2PService_ConnectClient, error) {
	stream, err := c.cc.NewStream(ctx, &P2PService_ServiceDesc.Streams[0], "/gop2pdme.P2PService/Connect", opts...)
	if err != nil {
		return nil, err
	}
	x := &p2PServiceConnectClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type P2PService_ConnectClient interface {
	Recv() (*Post, error)
	grpc.ClientStream
}

type p2PServiceConnectClient struct {
	grpc.ClientStream
}

func (x *p2PServiceConnectClient) Recv() (*Post, error) {
	m := new(Post)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *p2PServiceClient) Disconnect(ctx context.Context, in *Post, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/gop2pdme.P2PService/Disconnect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *p2PServiceClient) Messages(ctx context.Context, opts ...grpc.CallOption) (P2PService_MessagesClient, error) {
	stream, err := c.cc.NewStream(ctx, &P2PService_ServiceDesc.Streams[1], "/gop2pdme.P2PService/Messages", opts...)
	if err != nil {
		return nil, err
	}
	x := &p2PServiceMessagesClient{stream}
	return x, nil
}

type P2PService_MessagesClient interface {
	Send(*Post) error
	CloseAndRecv() (*Post, error)
	grpc.ClientStream
}

type p2PServiceMessagesClient struct {
	grpc.ClientStream
}

func (x *p2PServiceMessagesClient) Send(m *Post) error {
	return x.ClientStream.SendMsg(m)
}

func (x *p2PServiceMessagesClient) CloseAndRecv() (*Post, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Post)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// P2PServiceServer is the server API for P2PService service.
// All implementations must embed UnimplementedP2PServiceServer
// for forward compatibility
type P2PServiceServer interface {
	Connect(*Post, P2PService_ConnectServer) error
	Disconnect(context.Context, *Post) (*Empty, error)
	Messages(P2PService_MessagesServer) error
	mustEmbedUnimplementedP2PServiceServer()
}

// UnimplementedP2PServiceServer must be embedded to have forward compatible implementations.
type UnimplementedP2PServiceServer struct {
}

func (UnimplementedP2PServiceServer) Connect(*Post, P2PService_ConnectServer) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedP2PServiceServer) Disconnect(context.Context, *Post) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Disconnect not implemented")
}
func (UnimplementedP2PServiceServer) Messages(P2PService_MessagesServer) error {
	return status.Errorf(codes.Unimplemented, "method Messages not implemented")
}
func (UnimplementedP2PServiceServer) mustEmbedUnimplementedP2PServiceServer() {}

// UnsafeP2PServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to P2PServiceServer will
// result in compilation errors.
type UnsafeP2PServiceServer interface {
	mustEmbedUnimplementedP2PServiceServer()
}

func RegisterP2PServiceServer(s grpc.ServiceRegistrar, srv P2PServiceServer) {
	s.RegisterService(&P2PService_ServiceDesc, srv)
}

func _P2PService_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Post)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(P2PServiceServer).Connect(m, &p2PServiceConnectServer{stream})
}

type P2PService_ConnectServer interface {
	Send(*Post) error
	grpc.ServerStream
}

type p2PServiceConnectServer struct {
	grpc.ServerStream
}

func (x *p2PServiceConnectServer) Send(m *Post) error {
	return x.ServerStream.SendMsg(m)
}

func _P2PService_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Post)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(P2PServiceServer).Disconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gop2pdme.P2PService/Disconnect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(P2PServiceServer).Disconnect(ctx, req.(*Post))
	}
	return interceptor(ctx, in, info, handler)
}

func _P2PService_Messages_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(P2PServiceServer).Messages(&p2PServiceMessagesServer{stream})
}

type P2PService_MessagesServer interface {
	SendAndClose(*Post) error
	Recv() (*Post, error)
	grpc.ServerStream
}

type p2PServiceMessagesServer struct {
	grpc.ServerStream
}

func (x *p2PServiceMessagesServer) SendAndClose(m *Post) error {
	return x.ServerStream.SendMsg(m)
}

func (x *p2PServiceMessagesServer) Recv() (*Post, error) {
	m := new(Post)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// P2PService_ServiceDesc is the grpc.ServiceDesc for P2PService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var P2PService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gop2pdme.P2PService",
	HandlerType: (*P2PServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Disconnect",
			Handler:    _P2PService_Disconnect_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _P2PService_Connect_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Messages",
			Handler:       _P2PService_Messages_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/gop2pdme.proto",
}
